[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
data_dir = /var/lib/odoo
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
admin_passwd = $pbkdf2-sha512$600000$nhNibM05J2Ts3TsnRGjNGQ$jTKNZMdnLrWlokQlQyMKIuDza35/93ij8T/MzUVgUXTDMGuVVQoorDd1v9Gk4U0qT2TQm/nm0sQOqJs5QUTXgQ
proxy_mode = False
list_db = True
log_level = info
limit_time_real = 600
limit_time_real_cron = 600

