from . import (
    contract,
    dashboard,
    export_mixin,
    invoice_record,
    payment_record,
    project_start,
    receivable_plan,
    res_partner,
    service_record,
    site,
    soft_delete_mixin,
    ui_cleanup,
    warning_event,
    warning_rule,
)
