{
    "name": "ZFMD Project Management",
    "summary": "兆方美迪合同、项目执行与应收管理",
    "version": "17.0.1.5.0",
    "author": "Codex",
    "license": "LGPL-3",
    "category": "Sales",
    "depends": ["base", "mail", "web"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/sequence_data.xml",
        "data/dashboard_data.xml",
        "data/warning_rule_data.xml",
        "data/ui_cleanup.xml",
        "views/branding_templates.xml",
        "views/dashboard_views.xml",
        "views/warning_views.xml",
        "views/menu_views.xml",
        "views/search_views.xml",
        "views/export_actions.xml",
        "views/partner_actions.xml",
        "views/contract_import_wizard_views.xml",
        "views/invoice_import_wizard_views.xml",
        "views/payment_import_wizard_views.xml",
        "views/payment_period_export_wizard_views.xml",
        "views/project_start_import_wizard_views.xml",
        "views/receivable_import_wizard_views.xml",
        "views/service_record_import_wizard_views.xml",
        "views/backup_center_wizard_views.xml",
        "views/res_partner_views.xml",
        "views/site_views.xml",
        "views/contract_views.xml",
        "views/project_start_views.xml",
        "views/service_record_views.xml",
        "views/invoice_record_views.xml",
        "views/payment_record_views.xml",
        "views/receivable_plan_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "zfmd_pm/static/src/js/user_menu_patch.js",
            "zfmd_pm/static/src/scss/ui_cleanup.scss",
            "zfmd_pm/static/src/xml/navbar_cleanup.xml",
        ],
    },
    "application": True,
    "installable": True,
}
